config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :players, controllers: { omniauth_callbacks: 'players/omniauth_callbacks' }
  devise_scope :player do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_player_session
  end

  root to: 'home#index'
  get 'live_player/show'
  get 'code-of-conduct', to: 'static_pages#code_of_conduct'

  resources :players, only: [:index, :show, :update] do
    get 'rotate_token', on: :member
  end

  resources :matches, only: [:index, :show]
  resources :discord_channels, only: [:index, :show]

  namespace 'results' do
    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        resources :map_suggestions, only: [:index, :create]
        post 'map_suggestions/vote', to: 'map_suggestions#vote'
        resources :matches, only: [:create]
        post 'fo_login', to: 'fo_logins#create'
        post 'matches/:id', to: 'matches#update'
        resources :fair_teams, only: [:new]
      end

      namespace :v2 do
        post 'fo_login', to: 'fo_logins#create'
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @matches = Match.completed.limit(1)
  end
end

app/views/home/index.html.erb
<% content_for :banner do %>
  <div id="banner"></div>
<% end %>

<main class="container">
  <section>
    <hgroup>
    <h1>FortressOne</h1>
    <h2>Quake Team Fortress Remastered</h2>
    </hgroup>

    <p>Free and open source fork of the original 1996 QuakeWorld mod Team Fortress. Fast-paced, class based, arena first person shooter remastered with refined graphics, new mechanics and evolved gameplay.</p>
  </section>

  <section>
    <div class="grid">
      <div>
        <hgroup>
        <h2>Download</h2>
        <h3>Extract and run</h3>
        </hgroup>

        <p>Latest release (12 August 2023):</p>

        <ul>
          <li><a href="https://github.com/FortressOne/fte-config/releases/download/1.1.1-beta.3/fortressone-fte-windows-1.1.1-beta.3-portable.zip">Windows v1.1.1-beta.3</a></li>
          <li><a href="https://github.com/FortressOne/fte-config/releases/download/1.1.1-beta.3/fortressone-fte-linux-1.1.1-beta.3-portable.zip">Linux v1.1.1-beta.3</a></li>
        </ul>

        <p>Optional extras:</p>

        <ul>
          <li><a href="https://fortressone-share.s3.ap-southeast-2.amazonaws.com/hivis.zip">Hi vis models pack</a></br><small>Extract to <code>FortressOne/fortress/</code></small></li>
          <li><a href="https://fortressone-share.s3.ap-southeast-2.amazonaws.com/quake106_deiced.zip">Shareware Quake v1.06</a></li>
          <li><a href="https://maps.fortressone.org">Maps</a></li>
        </ul>

        <p>Pick-up games are organised on <a href="https://discord.fortressone.org">Discord</a>.
      </div>
      <div>
        <%= turbo_frame_tag :live_player_show, src: live_player_show_path, loading: :lazy do %>
          <%= render "video_frame", locals: { h2: "Watch", h3: "loading..." } do %>
            <div class="responsive-iframe">
              <div class="box"></div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </section>

  <section id="links">
    <div class="grid">
      <div>
        <hgroup>
        <h2>Video</h2>
        <h3>In game action</h3>
        </hgroup>
        <ul>
          <li><a href="https://www.youtube.com/channel/UCgYzKaEyTNoVfRLwlpfKzFQ">YouTube</a></li>
          <li><a href="https://www.twitch.tv/FortressOne">Twitch channel</a></li>
          <li><a href="https://www.twitch.tv/directory/game/FortressOne">Twitch category</a></li>
        </ul>
      </div>
      <div>
        <hgroup>
        <h2>Play</h2>
        <h3>Chat, code, learn</h3>
        </hgroup>
        <ul>
          <li><a href="https://discord.fortressone.org">Discord</a></li>
          <li><a href="https://github.com/fortressone">GitHub</a></li>
          <li><a href="https://github.com/FortressOne/wiki/wiki">Wiki</a></li>
        </ul>
      </div>
      <div>
        <hgroup>
        <h2>Featured</h2>
        <h3>Around the web</h3>
        </hgroup>
        <ul>
          <li><a href="https://www.moddb.com/games/fortressone">ModDB</a></li>
          <li><a href="https://drzel.itch.io/fortressone">itch.io</a></li>
          <li><a href="https://www.igdb.com/games/fortressone">IGDB</a></li>
        </ul>
      </div>
      <div>
        <hgroup>
        <h2>Social</h2>
        <h3>We got those too</h3>
        </hgroup>
        <ul>
          <li><a href="https://www.reddit.com/r/FortressOne">Reddit</a></li>
          <li><a href="https://twitter.com/fortressone_dev">Twitter</a></li>
          <li><a href="https://news.ycombinator.com/item?id=22777321">Hacker News</a></li>
        </ul>
      </div>
      <div>
        <hgroup>
        <h2>Posterity</h2>
        <h3>Nerd out on history</h3>
        </hgroup>
        <ul>
          <li><%= link_to("Match results", matches_path, rel: "nofollow") %></li>
          <li><a href="https://demos.fortressone.org">Demos</a></li>
          <li><a href="http://fortressone-stats.s3-website-ap-southeast-2.amazonaws.com/">Stats</a></li>
        </ul>
      </div>
    </div>
  </section>

  <section id="matches">
    <hgroup>
    <h2>Latest pick-up game result</h2>
    <h3>Games organised through Discord</h3>
    </hgroup>

    <% @matches.each do |match| %>
      <%= render match %>
    <% end %>
    <a href="/matches">See all match results</a>
  </section>

  <section id="screenshots">
    <hgroup>
    <h2>Screenshots</h2>
    <h3>Click to open</h3>
    </hgroup>

    <div class="grid">
      <div style="margin-bottom: 20px;">
        <%= link_to(asset_path("home/screenshots/1.png"), target:"_blank") do %>
          <%= image_tag(asset_path("home/screenshots/thumbnails/1.webp"), alt: "Heavy leaving spawn with team", width: "640", height: "360") %>
        <% end %>
      </div>
      <div style="margin-bottom: 20px;">
        <%= link_to(asset_path("home/screenshots/2.png"), target:"_blank") do %>
          <%= image_tag(asset_path("home/screenshots/thumbnails/2.webp"), alt: "Spy lobbing grenade at Engineer and sentry gun", width: "640", height: "360") %>
        <% end %>
      </div>
      <div style="margin-bottom: 20px;">
        <%= link_to(asset_path("home/screenshots/3.png"), target:"_blank") do %>
          <%= image_tag(asset_path("home/screenshots/thumbnails/3.webp"), alt: "Detonating pipe bombs to take out attacking medic", width: "640", height: "360") %>
        <% end %>
      </div>
    </div>
    <div class="grid">
      <div style="margin-bottom: 20px;">
        <%= link_to(asset_path("home/screenshots/4.png"), target:"_blank") do %>
          <%= image_tag(asset_path("home/screenshots/thumbnails/4.webp"), alt: "Heavy turns around to discover a spy", width: "640", height: "360") %>
        <% end %>
      </div>
      <div style="margin-bottom: 20px;">
        <%= link_to(asset_path("home/screenshots/5.png"), target:"_blank") do %>
          <%= image_tag(asset_path("home/screenshots/thumbnails/5.webp"), alt: "Soldier attacks enemy ramp room", width: "640", height: "360") %>
        <% end %>
      </div>
      <div style="margin-bottom: 20px;">
        <%= link_to(asset_path("home/screenshots/6.png"), target:"_blank") do %>
          <%= image_tag(asset_path("home/screenshots/thumbnails/6.webp"), alt: "Soldier throws grenade at enemy pyro", width: "640", height: "360") %>
        <% end %>
      </div>
    </div>
    <div class="grid">
      <div style="margin-bottom: 20px;">
        <%= link_to(asset_path("home/screenshots/7.png"), target:"_blank") do %>
          <%= image_tag(asset_path("home/screenshots/thumbnails/7.webp"), alt: "Enemy medic attempts to infect defending soldier", width: "640", height: "360") %>
        <% end %>
      </div>
      <div style="margin-bottom: 20px;">
        <%= link_to(asset_path("home/screenshots/8.png"), target:"_blank") do %>
          <%= image_tag(asset_path("home/screenshots/thumbnails/8.webp"), alt: "Heavy defends flag at front of base", width: "640", height: "360") %>
        <% end %>
      </div>
      <div style="margin-bottom: 20px;">
        <%= link_to(asset_path("home/screenshots/9.png"), target:"_blank") do %>
          <%= image_tag(asset_path("home/screenshots/thumbnails/9.webp"), alt: "Demo and soldier fire on outgoing spy", width: "640", height: "360") %>
        <% end %>
      </div>
    </div>
  </section>

  <section id="testimonials">
    <hgroup>
    <h2>Words</h2>
    <h3>What people are saying about FortressOne</h3>
    </hgroup>
    <blockquote>
      "Possibly the best game ever made!"
      <footer>
        <cite>- hydr0buds</cite>
      </footer>
    </blockquote>
    <blockquote>
      "FortressOne has brought qwtf current both with improved graphics and slightly tweaked gameplay. The community on discord is very friendly and happy to help you get setup and running quickly. They organize pick up games every night and also setup tournaments."
      <footer>
        <cite>- a2yay</cite>
      </footer>
    </blockquote>
    <blockquote>
      "This is the game you played 20 years ago and fell in love with!"
      <footer>
        <cite>- ricksonfold</cite>
      </footer>
    </blockquote>
    <blockquote>
      "An outstanding mod with a lot of work going in to improve game play still till this day."
      <footer>
        <cite>- andywelsh17</cite>
      </footer>
    </blockquote>
  </section>

  <section id="classes" data-nosnippet>
    <hgroup>
    <h2>Classes</h2>
    <h3>The low-down on each</h3>
    </hgroup>

    <% Playerclass.all.each do |playerclass_id, playerclass| %>
      <article>
        <div style="display: flex;">
          <div style="flex: 33%">
            <h3><%= "#{playerclass_id}. #{playerclass[:name]}" %></h3>
            <% playerclass[:images].each do |_colour, image| %>
              <%= image_tag(image[:url], alt: image[:alt]) %>
            <% end %>
          </div>
          <div style="flex: 33%">
            <dl>
              <dt>Speed</dt>
              <dd><%= playerclass[:speed] %> unit/s</dd>
            </dl>
            <dl>
              <dt>Armour</dt>
              <dd><%= playerclass[:armour] %></dd>
            </dl>
            <dl>
              <dt>Specials</dt>
              <dd>
                <ol>
                  <% playerclass[:specials].each do |special| %>
                    <li><%= special %></li>
                  <% end %>
                </ol>
              </dd>
            </dl>
            <% if playerclass[:attributes].any? %>
              <dl>
                <dt>Attributes</dt>
                <dd>
                  <ul>
                    <% playerclass[:attributes].each do |weapon| %>
                      <li><%= weapon.presence || "-" %></li>
                    <% end %>
                  </ul>
                </dd>
              </dl>
            <% end %>
          </div>
          <div style="flex: 33%">
            <dl>
              <dt>Weapons</dt>
              <dd>
                <ol>
                  <% playerclass[:weapons].each do |weapon| %>
                    <li><%= weapon %></li>
                  <% end %>
                </ol>
              </dd>
            </dl>
            <dl>
              <dt>Grenades</dt>
              <dd>
                <ol>
                  <% playerclass[:grenades].each do |grenade| %>
                    <li><%= grenade %></li>
                  <% end %>
                </ol>
              </dd>
            </dl>
          </div>
        </div>
      </article>
    <% end %>
  </section>

  <section id="controls">
    <hgroup>
    <h2>Controls</h2>
    <h3>There's a lot of buttons</h3>
    </hgroup>
    <%= image_tag(asset_path("home/controls.webp"), alt: "Default keyboard config") %>
  </section>

  <section id="acknowledgements">
    <hgroup>
    <h2>Acknowledgments</h2>
    <h3>A true grassroots community project</h3>
    </hgroup>
    <div class="grid">
      <div>
        <p>FortressOne is powered by:</p>
        <ul>
          <li><a href="https://fte.triptohell.info/">FTE Quake</a></li>
          <li><a href="https://web.archive.org/web/20131005123834/http://www.planetfortress.com/teamfortress/">Team Fortress</a></li>
          <li><a href="https://bethesda.net/en/game/quake">QuakeWorld</a></li>
          <li><a href="https://web.archive.org/web/20210401101846/https://classicfortress.net/">Classic Fortress</a></li>
        </ul>
      </div>
      <div>
        <p>It includes assets from:</p>
        <ul>
          <li><a href="https://github.com/MissLav/LibreQuake">LibreQuake</a></li>
          <li><a href="http://openquartz.sourceforge.net/index.html">OpenQuartz</a></li>
          <li><a href="https://qrp.quakeone.com/">Quake Revitalisation Project</a></li>
          <li><a href="https://www.quaddicted.com/webarchive/www.planetfortress.com/tfdone_easy/dox/index.html">DOX's Coolcrap</a></li>
          <li><a href="http://members.optusnet.com.au/~plaguespak/">Plagues pak</a></li>
          <li><a href="https://web.archive.org/web/20131029220657/http://ruohis.com/home.htm">Ruohis</a></li>
          <li><a href="https://gfx.quakeworld.nu/user/148/primevil/">PrimeviL</a></li>
          <li><a href="https://gfx.quakeworld.nu/user/26/bps/">bps</a></li>
        </ul>
      </div>
      <div>
        <p>It takes inspiration from:</p>
        <ul>
          <li><a href="https://web.archive.org/web/20120210172357/http://zquake.frag.ru/eng/news/index.shtml">zQuake</a></li>
          <li><a href="https://web.archive.org/web/20060820054509/http://www.fuhquake.net/">FuhQuake</a></li>
          <li><a href="https://www.ezquake.com/">ezQuake</a></li>
          <li><a href="https://web.archive.org/web/20050627020628/http://ap.qgl.org/mercury/">ozTF</a></li>
          <li><a href="https://github.com/gmtandi/huetf">hueTF</a></li>
          <li><a href="https://www.quakelive.com/">Quake Live</a></li>
          <li><a href="https://store.steampowered.com/app/20/Team_Fortress_Classic/">Team Fortress Classic</a></li>
          <li><a href="http://www.fortress-forever.com/">Fortress Forever</a></li>
          <li><a href="https://www.teamfortress.com/">Team Fortress 2</a></li>
        </ul>
      </div>
    </div>
  </section>
</main>

<footer class="container">
  <p>FortressOne <%= Time.zone.now.year %><%= DELIMITER %><%= link_to("Code of conduct", code_of_conduct_path) %></p>
</footer>