config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :players, controllers: { omniauth_callbacks: 'players/omniauth_callbacks' }
  devise_scope :player do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_player_session
  end

  root to: 'home#index'
  get 'live_player/show'
  get 'code-of-conduct', to: 'static_pages#code_of_conduct'

  resources :players, only: [:index, :show, :update] do
    get 'rotate_token', on: :member
  end

  resources :matches, only: [:index, :show]
  resources :discord_channels, only: [:index, :show]

  namespace 'results' do
    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        resources :map_suggestions, only: [:index, :create]
        post 'map_suggestions/vote', to: 'map_suggestions#vote'
        resources :matches, only: [:create]
        post 'fo_login', to: 'fo_logins#create'
        post 'matches/:id', to: 'matches#update'
        resources :fair_teams, only: [:new]
      end

      namespace :v2 do
        post 'fo_login', to: 'fo_logins#create'
      end
    end
  end
end

app/models/player.rb
class Player < ApplicationRecord
  include ResultConstants

  IMAGES = [
    "blue_demoman.webp",
    "blue_engineer.webp",
    "blue_hwguy.webp",
    "blue_medic.webp",
    "blue_pyro.webp",
    "blue_scout.webp",
    "blue_sniper.webp",
    "blue_soldier.webp",
    "blue_spy.webp",
    "red_demoman.webp",
    "red_engineer.webp",
    "red_hwguy.webp",
    "red_medic.webp",
    "red_pyro.webp",
    "red_scout.webp",
    "red_sniper.webp",
    "red_soldier.webp",
    "red_spy.webp",
  ]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable

  devise :rememberable, :omniauthable, omniauth_providers: %i[discord]

  has_many :discord_channel_players, dependent: :destroy
  has_many :discord_channels, through: :discord_channel_players
  has_many :discord_channel_player_teams, through: :discord_channel_players
  has_many :teams, through: :discord_channel_player_teams
  has_many :matches, through: :teams

  has_secure_token :auth_token

  scope :visible, ->{ where(invisible: false) }

  def self.from_omniauth(auth)
    player = find_or_initialize_by(discord_id: auth.uid)
    player.email = auth.info.email
    # player.password = Devise.friendly_token[0, 20]
    player.name = auth.info.name
    player.image = auth.info.image || "home/classes/#{IMAGES.sample}"
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    # player.skip_confirmation!
    player.save
    player
  end

  def get_auth_token
    self.regenerate_auth_token if self.auth_token.nil?
    self.auth_token
  end

  def last_match_date
    teams.sort_by(&:created_at).last&.created_at
  end

  def discord_channel_players_with_matches_played
    discord_channel_players
      .sort_by(&:match_count)
      .reverse
      .filter do |dcp|
      dcp.teams.any?
    end
  end

  def match_count
    win_count + loss_count + draw_count
  end

  def win_count
    discord_channel_players.sum { |dcp| dcp.winning_teams_count }
  end

  def loss_count
    discord_channel_players.sum { |dcp| dcp.losing_teams_count }
  end

  def draw_count
    discord_channel_players.sum { |dcp| dcp.drawing_teams_count }
  end
end

app/controllers/players/omniauth_callbacks_controller.rb
class Players::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include Devise::Controllers::Rememberable

  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: :discord

  def discord
    @player = Player.from_omniauth(request.env["omniauth.auth"])

    discord_user = begin
      Discordrb::API::Server.resolve_member(
        "Bot #{Rails.application.credentials.discord[:token]}",
        Rails.application.config.discord[:server_id],
        request.env["omniauth.auth"]["uid"]
      )
    rescue Discordrb::Errors::UnknownMember
      Discordrb::API::User.resolve(
        "Bot #{Rails.application.credentials.discord[:token]}",
        request.env["omniauth.auth"]["uid"]
      )
    end

    json = JSON.parse(discord_user)

    name = json["nick"] ||
      (json["user"] && json["user"]["username"]) ||
      json["display_name"] ||
      json["global_name"] ||
      json["username"]

    @player.update(name: name)

    if @player.persisted?
      sign_in_and_redirect @player, event: :authentication # this will throw if @player is not activated
      set_flash_message(:notice, :success, kind: "discord") if is_navigational_format?
    else
      session["devise.discord_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_player_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  add_breadcrumb "Home", :root_path

  before_action :set_player, only: [:update, :rotate_token]
  before_action :authorize_player, only: [:update, :rotate_token]

  def index
    @players = Player
      .joins(:teams)
      .includes(:teams)
      .sort_by(&:last_match_date)
      .reverse

    add_breadcrumb "Players"
  end

  def show
    @player = Player
      .includes(
        [
          { discord_channel_players: [
            :trueskill_ratings,
            { discord_channel: { discord_channel_players: [:trueskill_rating] } },
            { discord_channel_player_teams: [:team, :trueskill_rating] }
          ] },
        ]
      ).find(params[:id])

    add_breadcrumb "Players", players_path
    add_breadcrumb @player.name
  end

  def update
    if @player.update(player_params)
      render json: { status: :ok }
    else
      render json: @player.errors, status: :unprocessable_entity
    end
  end

  def rotate_token
    current_player.regenerate_auth_token
    redirect_to player_path(@player), notice: "Token has been rotated."
  end

  private

  def authorize_player
    if @player != current_player
      render(
        json: { error: 'Not Authorized' },
        status: 403
      )
    end
  end

  def player_params
    params.require(:player).permit(:public_ratings)
  end

  def set_player
    @player = Player.find(params[:id])
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/index.html.erb
<main class="container-wide">
  <%= render_breadcrumbs %>
  <h2>Players</h2>

  <figure>
    <table id="players_table" style="white-space: nowrap;" role="grid">
      <thead>
        <tr>
          <th style="width: 1.5rem;"></th>
          <th>Name</th>
          <th data-sort-method='number'>Played</th>
          <th data-sort-method='number'>Wins</th>
          <th data-sort-method='number'>Losses</th>
          <th data-sort-method='number'>Draws</th>
          <th data-sort-method='number'>Last Match Date</th>
        </tr>
      </thead>
      <tbody>
        <% @players.each do |player| %>
          <td>
            <% if player.image %>
              <%= image_tag player.image, style: "max-width: 1.5rem; border-radius: 50%;" %>
            <% end %>
          </td>
          <td><%= link_to(player.name, player) %></td>
          <td><%= player.match_count %></td>
          <td><%= player.win_count %></td>
          <td><%= player.loss_count %></td>
          <td><%= player.draw_count %></td>
          <td data-sort="<%= player.last_match_date && player.last_match_date.to_i %>">
            <%= player.last_match_date && local_time_ago(player.last_match_date) %>
          </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </figure>
</main>

app/views/players/show.html.erb
<main class="container">
  <%= render_breadcrumbs %>

  <div style="display: flex; gap: 1rem; margin-bottom: 30px;">
    <% if @player.image %>
      <%= image_tag @player.image, style: "margin-top: 0.5rem; border-radius: 50%;" %>
    <% end %>

    <hgroup>
    <h2><%= @player.name %></h2>
    <h3>
      Has played <%= @player.match_count %> matches</br>
      Last played <%= @player.last_match_date && local_time_ago(@player.last_match_date) %>
    </h3>
    </hgroup>
  </div>

  <% if @player == current_player || current_player&.admin? %>
    <p>
      Connect to a FortressOne server and enter
      <code>/login <%= @player.auth_token %></code>
      at the console.
      <%= link_to("Rotate token", rotate_token_player_path, data: {turbo: false}) %>
    </p>

    <fieldset>
      <label for="public_ratings">
        <div data-controller="toggle" data-toggle-url="<%= player_path(@player) %>" data-toggle-value="<%= @player.public_ratings %>">
          <input name="public_ratings" type="checkbox" data-action="click->toggle#toggle" data-toggle-target="checkbox">
          Publish ratings? Checking this box also allows you to see other public ratings.
        </div>
      </label>
    </fieldset>
  <% end %>

  <figure>
    <table id="player_table" style="white-space: nowrap; max-width: 200px;" role="grid">
      <thead>
        <tr>
          <td>Played</td>
          <td>Wins</td>
          <td>Losses</td>
          <td>Draws</td>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @player.match_count %></td>
          <td><%= @player.win_count %></td>
          <td><%= @player.loss_count %></td>
          <td><%= @player.draw_count %></td>
        </tr>
      </tbody>
    </table>
  </figure>


  <% @player.discord_channel_players_with_matches_played.each do |dcp| %>
    <section>
      <figure>
        <%= link_to dcp.discord_channel.name, discord_channel_path(dcp.discord_channel) %>
        <table id="player_discord_channels_table" style="white-space: nowrap;" role="grid">
          <thead>
            <tr>
              <% if (current_player&.public_ratings? && @player.public_ratings?) || @player == current_player || current_player&.admin? %>
                <th data-sort-method='number'>CSE</th>
                <th>Tier</th>
                <th data-sort-method='number'>Rank</th>
                <th data-sort-method='dotsep'>Percentile</th>
              <% end %>
              <th data-sort-method='number'>Played</th>
              <th data-sort-method='number'>Wins</th>
              <th data-sort-method='number'>Losses</th>
              <th data-sort-method='number'>Draws</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <% if (current_player&.public_ratings? && @player.public_ratings?) || @player == current_player || current_player&.admin? %>
                <td><%= number_with_precision(dcp.conservative_skill_estimate, precision: 2) %></td>
                <td><%= dcp.tier %></td>
                <td><%= dcp.rank %>/<%= dcp.discord_channel.discord_channel_players.count %></td>
                <td><%= dcp.percentile.to_i.ordinalize %></td>
              <% end %>
              <td><%= dcp.match_count %></td>
              <td><%= dcp.win_count %></td>
              <td><%= dcp.loss_count %></td>
              <td><%= dcp.draw_count %></td>
            </tr>
          </tbody>
        </table>
          <% if (current_player&.public_ratings? && @player.public_ratings?) || @player == current_player || current_player&.admin? %>
          <%= area_chart(
            dcp.trueskill_ratings_graph(60),
            xmin: 1,
            xmax: 60,
            height: "300px",
            min: nil,
            xtitle: "Last 60 matches",
            ytitle: "Conservative skill estimate") %>
      </figure>
    <% end %>
    </section>
  <% end %>
</main>