config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :players, controllers: { omniauth_callbacks: 'players/omniauth_callbacks' }
  devise_scope :player do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_player_session
  end

  root to: 'home#index'
  get 'live_player/show'
  get 'code-of-conduct', to: 'static_pages#code_of_conduct'

  resources :players, only: [:index, :show, :update] do
    get 'rotate_token', on: :member
  end

  resources :matches, only: [:index, :show]
  resources :discord_channels, only: [:index, :show]

  namespace 'results' do
    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        resources :map_suggestions, only: [:index, :create]
        post 'map_suggestions/vote', to: 'map_suggestions#vote'
        resources :matches, only: [:create]
        post 'fo_login', to: 'fo_logins#create'
        post 'matches/:id', to: 'matches#update'
        resources :fair_teams, only: [:new]
      end

      namespace :v2 do
        post 'fo_login', to: 'fo_logins#create'
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html data-theme="dark">
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-SCSMVJXDGJ"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-SCSMVJXDGJ');
    </script>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>FortressOne - Quake Team Fortress Remastered</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="description" content="Free, open source fork of the original 1996 QuakeWorld mod Team Fortress. It is a fast-paced, class based, arena first person shooter remastered with refined graphics, new mechanics and evolved gameplay." />

    <%= stylesheet_link_tag 'https://unpkg.com/@picocss/pico@1.5.12/css/pico.min.css', media: 'all', 'data-turbo-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>

    <%= javascript_include_tag "https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js" %>
    <%= javascript_include_tag "https://unpkg.com/tablesort@5.3.0/dist/sorts/tablesort.number.min.js" %>
    <%= javascript_importmap_tags %>

    <link rel="apple-touch-icon" sizes="180x180" href="/images/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/favicons/favicon-16x16.png">
    <link rel="manifest" href="/images/favicons/site.webmanifest">
    <link rel="mask-icon" href="/images/favicons/safari-pinned-tab.svg" color="#5bbad5">
    <link rel="shortcut icon" href="/images/favicons/favicon.ico">
  </head>

  <body>
    <%= content_for :banner %>
    <nav class="container">
      <ul>
        <li>
          <%= link_to "/" do %>
            <%= image_tag(asset_path("home/logo.webp"), alt: "FortressOne logo", height: 128, width: 128) %>
          <% end %>
        </li>
      </ul>
      <ul>
        <% if player_signed_in? %>
          <li>Signed in as <%= link_to(current_player.name, current_player) %></li>

          <% if current_player.image %>
            <li><%= image_tag current_player.image, style: "max-height: 3rem; border-radius: 50%;" %></li>
          <% end %>

          <li>
            <%= button_to(
              "Sign out",
              destroy_player_session_path,
              method: :delete,
              data: { turbo: false },
              role: :button,
              class: "secondary",
              form: { style: "margin-bottom: 0px;" }
            )%>
          </li>
        <% else %>
          <li>
            <%= button_to(
              "Sign in with Discord",
              player_discord_omniauth_authorize_path,
              data: { turbo: false },
              role: :button,
              class: "secondary",
              form: { style: "margin-bottom: 0px;" }
            ) %>
          </li>
        <% end %>
      </ul>
    </nav>

    <% if [notice, alert].any? %>
      <section class="container">
        <% if notice %>
          <small><%= notice %></small>
        <% end %>

        <% if alert %>
          <small><%= alert %></small>
        <% end %>
      </section>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/ratings.html.erb
<% content_for :stylesheets do %>
  <link rel="stylesheet" href="/ratings/stylesheets/ratings.css">
<% end %>

<%= render template: "layouts/application" %>